[package]
name = "rankcorcoef"
version = "0.1.0"
authors = ["DESKTOP-1RH0QUC\\magip <magipripmail.goo.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
